[tool.poetry]
name = "pysparklabs"
version = "0.1.0"
description = ""
authors = ["Marcelo Ribas <marcelo.pachione@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
